### ISSUE TITLE
apktool not working on Linux

### ISSUE THREAD

**Issue by learntheropes** [zapstore/zapstore-cli#24]
When running `zapstore publish peach --overwrite-release` I get this error:

```
Publishing Peach Bitcoin android app...
✔ Fetched metadata from Github
✔ Fetched package: https://github.com/Peach2Peach/peach-app/releases/download/v0.5.0/app-prod-arm64-v8a-release.apk
⠋ Parsing APK...
ERROR ShellException(sh -c "/home/learntheropes/.zapstore/apktool decode -s -f -o /tmp/eca8b9cd8281377a52dccc8151615ade58fc9ab4ed0cc9fb534b9e2fae63c0e2 /tmp/eca8b9cd8281377a52dccc8151615ade58fc9ab4ed0cc9fb534b9e2fae63c0e2.apk", exitCode 1, workingDirectory: /home/learntheropes/Documents/Dev/peach-bitcoin/zapstore-cli)
```

My `zapstore.yaml`:
```yaml
peach:
  android:
    name: Peach Bitcoin
    description: Buy Bitcoin Without KYC
    repository: https://github.com/Peach2Peach/peach-app
    artifacts:
      - app-prod-arm64-v8a-release.apk
```
