### ISSUE TITLE
Invalid tag for mapping

### ISSUE THREAD

**Issue by v0l** [zapstore/zapstore-cli#32]
Trying to publish snort:

```yaml
snort:
  android:
    repository: https://github.com/v0l/snort
    name: Snort
    artifacts:
      - snort-universal-v%v.apk
```

Getting this error:

```bash
 ERROR Error on line 1, column 1: Invalid tag for mapping.
  ╷
1 │ !!brut.androlib.meta.MetaInfo
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
#0      Loader._loadMapping (package:yaml/src/loader.dart:159)
#1      Loader._loadNode (package:yaml/src/loader.dart:92)
#2      Loader._loadDocument (package:yaml/src/loader.dart:68)
#3      Loader.load (package:yaml/src/loader.dart:60)
#4      loadYamlDocument (package:yaml/yaml.dart:72)
#5      loadYamlNode (package:yaml/yaml.dart:57)
#6      loadYaml (package:yaml/yaml.dart:44)
#7      parseApk (package:zapstore_cli/commands/publish/apk.dart:65)
<asynchronous suspension>
#8      publish (package:zapstore_cli/commands/publish.dart:149)
<asynchronous suspension>
#9      PublishCommand.run (package:zapstore_cli/main.dart:175)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#11     main (package:zapstore_cli/main.dart:37)
<asynchronous suspension>
```
