### ISSUE TITLE
tmp file not found

### ISSUE THREAD

**Issue by v0l** [zapstore/zapstore-cli#35]
Trying to publish freeflow i get the following message

```bash
Publishing Freeflow android app...
✔ Fetched metadata from Github
✔ Fetched package: https://github.com/nostrlabs-io/freeflow/releases/download/v0.1.1/app-armeabi-v7a-release.apk
✔ Fetched package: https://github.com/nostrlabs-io/freeflow/releases/download/v0.1.1/app-arm64-v8a-release.apk
✔ Fetched package: https://github.com/nostrlabs-io/freeflow/releases/download/v0.1.1/app-x86_64-release.apk
⠸ Parsing APK...
ERROR PathNotFoundException: Cannot open file, path = '/tmp/17d83476c404041adc88b1dbc90c192242467d2c1acd18dd71f0328df42dfbfd.apktool/AndroidManifest.xml' (OS Error: No such file or directory, errno = 2)

#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562)
<asynchronous suspension>
#3      _File.readAsString (dart:io/file_impl.dart:621)
<asynchronous suspension>
#4      parseApk (package:zapstore_cli/commands/publish/apk.dart:56)
<asynchronous suspension>
#5      publish (package:zapstore_cli/commands/publish.dart:149)
<asynchronous suspension>
#6      PublishCommand.run (package:zapstore_cli/main.dart:175)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#8      main (package:zapstore_cli/main.dart:37)
<asynchronous suspension>


```

**Comment by franzaps** [comment]
Dang, sorry you're having so many issues. I'll try to reproduce on Ubuntu today or tomorrow

**Comment by franzaps** [comment]
Could you please share the `zapstore.yaml` you are using for Freeflow? 

I used the one you shared for Snort in a clean Ubuntu 22.04 installation and it works: https://blob.satellite.earth/ab8a4285882ffec90ca8d45081675f0dc943ab7dcd7c8d7791f32969c2c3f7b0

(I did fix `zapstore install apktool` today, but you mentioned you were on the latest)

What OS are you running?

These are the commands I used in the video:

```bash
# download zapstore-cli for linux
./zapstore-0.1.2-linux-aarch64 install apktool
# configure PATH for zapstore-cli

zapstore install apktool
sudo apt install openjdk-17-jre
sudo apt install apksigner # if you don't have it already available in android tools!
zapstore publish snort
```

**Comment by v0l** [comment]
OS: `Ubuntu 24.04.1 LTS`
Apktoo: `Apktool 2.10.0`
Apksigner: `apksigner 0.9`
Java: `openjdk 21.0.6 2025-01-21`


```yaml
freeflow:
  android:
    identifier: io.nostrlabs.freeflow
    name: Freeflow
    summary: A TikTok Clone in Flutter and nostr
    repository: https://github.com/nostrlabs-io/freeflow
    license: MIT
    builder: npub1v0lxxxxutpvrelsksy8cdhgfux9l6a42hsj2qzquu2zk7vc9qnkszrqj49
    artifacts:
      app-armeabi-v7a-release.apk:
        platform: armeabi-v7a
      app-arm64-v8a-release.apk:
        platform: arm64-v8a
      app-x86_64-release.apk:
        platform: x86_64
```

**Comment by franzaps** [comment]
That configuration is not good, please see the docs: https://zapstore.dev/docs/cli/publish/

Try this:

```yaml
freeflow:
  android:
    name: Freeflow
    summary: A TikTok Clone in Flutter and nostr
    repository: https://github.com/nostrlabs-io/freeflow
    license: MIT
    artifacts:
      - app-arm64-v8a-release.apk
```

`armeabi-v7a` and `x86_64` are not supported yet.
